enum RouteKeys {
  HOME = 'HOME',
  HOME_TAB = 'HOME_TAB',
  PAYMENTS_TAB = 'PAYMENTS_TAB',
  PAYMENTS_TRANSFER = 'PAYMENTS_TRANSFER',
  PAYMENTS_CONFIRMATION = 'PAYMENTS_CONFIRMATION',
  PAYMENTS_FAILED = 'PAYMENTS_FAILED',
  ACCOUNTS = 'ACCOUNTS',
}

export default RouteKeys;
